import type { Answers, Track } from '../data/types'
import type { Attribution } from './analytics'
import type { SignalId } from '../data/signals'

/**
 * Typed client for the Laravel API. In development Vite proxies /api to
 * Laravel; in production Nginx serves both from one origin. VITE_API_BASE_URL
 * can point elsewhere if the API lives on another host.
 */
const API_BASE = (import.meta.env.VITE_API_BASE_URL ?? '').replace(/\/$/, '')

export class ApiError extends Error {
  readonly status: number
  readonly code: string
  readonly body: Record<string, unknown>

  constructor(status: number, code: string, body: Record<string, unknown> = {}) {
    super(code)
    this.status = status
    this.code = code
    this.body = body
  }

  get isNetwork() {
    return this.status === 0
  }
}

async function request<T>(method: 'GET' | 'POST' | 'DELETE', path: string, body?: unknown): Promise<{ status: number; data: T }> {
  let response: Response
  try {
    response = await fetch(`${API_BASE}/api${path}`, {
      method,
      headers: { Accept: 'application/json', ...(body !== undefined ? { 'Content-Type': 'application/json' } : {}) },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    })
  } catch {
    throw new ApiError(0, 'network_error')
  }

  if (response.status === 204) return { status: 204, data: undefined as T }

  const data = (await response.json().catch(() => ({}))) as Record<string, unknown>

  if (!response.ok) {
    const code = typeof data.code === 'string' ? data.code : response.status === 422 ? 'validation_failed' : `http_${response.status}`
    throw new ApiError(response.status, code, data)
  }

  return { status: response.status, data: data as T }
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type AssessmentStatus = 'created' | 'payment_pending' | 'paid' | 'generating' | 'completed' | 'failed'

export interface AppConfig {
  price: number
  currency: string
}

export interface TeaserPayload {
  strengths: SignalId[]
  explore: SignalId[]
  attention: SignalId | null
}

export interface AssessmentSummary {
  status: AssessmentStatus
  paid: boolean
  teaser: { strengths: string[]; explore: string[]; attention: string | null }
  track: Track
  created_at: string
}

export interface BankDeeplink {
  name: string
  description: string | null
  logo: string | null
  link: string
}

export interface InvoiceDisplay {
  qr_text: string
  qr_image: string | null
  short_url: string | null
  deeplinks: BankDeeplink[]
}

export type PaymentResponse =
  | { status: 'paid'; assessment_status: AssessmentStatus }
  | {
      status: 'pending'
      assessment_status: AssessmentStatus
      amount: number
      currency: string
      invoice: InvoiceDisplay | null
      dev_bypass: boolean
    }

export interface PaymentStatusResponse {
  status: 'paid' | 'pending'
  assessment_status: AssessmentStatus
}

export type SectionState = 'strength' | 'mixed' | 'attention'

/** Reading order for report topics: what needs attention first, then mixed, then what's going well. */
export const STATE_ORDER: SectionState[] = ['attention', 'mixed', 'strength']

/**
 * One topic of the report. Current reports use insight/healthy/steps/try_saying;
 * summary/observations/tip exist only on reports generated by earlier versions.
 */
export interface ReportEvidence {
  question: string
  answer: string
}

export interface CheckInComparison {
  status: 'baseline' | 'compared'
  previous_date?: string
  current_date?: string
  days_between?: number
  stage_changed?: boolean
  items: {
    topic: string
    label: string
    previous: string | null
    current: string | null
    direction: 'improved' | 'declined' | 'unchanged' | 'not_comparable'
  }[]
}

export interface ReportSection {
  evidence?: ReportEvidence[]
  uncertainty?: string
  state?: SectionState
  insight?: string
  healthy?: string
  steps?: string[]
  try_saying?: string
  summary?: string
  observations?: string[]
  tip?: string
}

/** Early-stage "is this going to work?" read — signals so far, never a guarantee. */
export type PotentialLevel = 'promising' | 'unclear' | 'mixed_signals'

export interface RelationshipReport {
  evidence?: ReportEvidence[]
  uncertainty?: string
  /** Absent on reports created before early-stage reports existed (those are "couple"). */
  track?: Track
  headline: string
  summary: string
  strengths: { title: string; description: string }[]
  areas_to_explore: { title: string; description: string; importance: 'low' | 'moderate' | 'high' }[]
  // Couple topics
  communication?: ReportSection
  affection?: ReportSection
  effort?: ReportSection
  trust?: ReportSection
  conflict?: ReportSection
  independence?: ReportSection
  future?: ReportSection
  // Early-stage topics
  interest?: ReportSection
  consistency?: ReportSection
  connection?: ReportSection
  intentions?: ReportSection
  respect?: ReportSection
  values?: ReportSection
  feelings?: ReportSection
  /** Early stage only. */
  potential?: { level: PotentialLevel; title: string; explanation: string }
  green_flags?: string[]
  red_flags?: string[]
  patterns: { title: string; description: string }[]
  conversation_starters: string[]
  closing: string
  /** Added in the counselling-style report; absent on older reports. */
  note_to_you?: string
  action_plan?: { title: string; description: string }[]
  self_care?: string[]
}

export type PartnerShareSection = 'strengths' | 'areas_to_explore' | 'conversation_starters'
export interface PartnerShareContent {
  strengths?: { title: string; description: string }[]
  areas_to_explore?: { title: string; description: string }[]
  conversation_starters?: string[]
}
export interface PartnerShare {
  token: string
  content: PartnerShareContent
}

export type ReportState =
  | { status: 'completed'; report: RelationshipReport; created_at: string; comparison?: CheckInComparison }
  | { status: 'paid' | 'generating' }

// ---------------------------------------------------------------------------
// Endpoints
// ---------------------------------------------------------------------------

export const api = {
  getPartnerShare: (token: string) => request<{ share: PartnerShare | null }>('GET', `/assessments/${token}/partner-share`).then((r) => r.data.share),
  createPartnerShare: (token: string, sections: PartnerShareSection[]) => request<{ share: PartnerShare }>('POST', `/assessments/${token}/partner-share`, { sections }).then((r) => r.data.share),
  revokePartnerShare: (token: string) => request<void>('DELETE', `/assessments/${token}/partner-share`),
  getSharedReport: (token: string) => request<{ content: PartnerShareContent }>('GET', `/shared-reports/${token}`).then((r) => r.data.content),
  config: () => request<AppConfig>('GET', '/config').then((r) => r.data),

  createAssessment: (payload: {
    questionnaire_version: string
    answers: Answers
    teaser: TeaserPayload
    previous_assessment_token?: string | null
    attribution?: Attribution
  }) =>
    request<{ token: string; status: AssessmentStatus }>('POST', '/assessments', payload).then((r) => r.data),

  getAssessment: (token: string) => request<AssessmentSummary>('GET', `/assessments/${token}`).then((r) => r.data),

  deleteAssessment: (token: string) => request<void>('DELETE', `/assessments/${token}`).then(() => undefined),

  createPayment: (token: string) => request<PaymentResponse>('POST', `/assessments/${token}/payment`).then((r) => r.data),

  paymentStatus: (token: string) =>
    request<PaymentStatusResponse>('GET', `/assessments/${token}/payment-status`).then((r) => r.data),

  devMarkPaid: (token: string) =>
    request<PaymentStatusResponse>('POST', `/assessments/${token}/dev/mark-paid`).then((r) => r.data),

  generateReport: (token: string) => request<ReportState>('POST', `/assessments/${token}/generate-report`).then((r) => r.data),

  getReport: (token: string) => request<ReportState>('GET', `/assessments/${token}/report`).then((r) => r.data),
}

/** Tokens are 48 lowercase hex characters; anything else is rejected before calling the API. */
export function isValidToken(token: string | undefined): token is string {
  return typeof token === 'string' && /^[a-f0-9]{48}$/.test(token)
}
